include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    document_ignores: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
analyzer:
  exclude:
    - lib/generated/**
    - lib/**/*.g.dart
    - pubspec.yaml
