name: mimemo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Location
  geolocator: ^14.0.1

  # Notification
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

  # Local data
  shared_preferences: ^2.5.3

  # Route
  auto_route: ^10.1.0+1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_bloc: ^9.1.1

  # Model
  equatable: ^2.0.7
  json_annotation: ^4.9.0

  # Api
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # DI
  get_it: ^8.0.3

  # Others
  google_mobile_ads: ^6.0.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.5

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.1.0



flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
